##Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

##Separate Features and Target


In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ttrain = y_train.reshape(len(y_train), 1)
ttest = y_test.reshape(len(y_test), 1)

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
xdt_train = x_sc.fit_transform(x_train)
ydt_train = y_sc.fit_transform(ttrain)

In [ ]:
xdt_test = x_sc.transform(x_test)
ydt_test = y_sc.transform(ttest)

In [ ]:
xdt_train

array([[-0.54093053, -0.18247677, -0.02815116, ...,  0.27139469,
        -0.18305368,  1.47565337],
       [-1.28191355,  0.38434238, -1.35412642, ...,  1.37809665,
        -0.58317076,  0.91317161],
       [-0.36993445,  0.10093281, -0.0791502 , ..., -0.31450634,
        -0.41169201, -0.68052669],
       ...,
       [-0.76892531,  0.55438812, -0.99713308, ...,  1.11769619,
        -0.75464951, -1.33675541],
       [ 0.48504596,  0.61107004, -0.33414545, ..., -0.18430611,
        -0.46885159, -0.77427365],
       [-0.31293575,  0.15761472, -1.40512547, ..., -0.31450634,
        -0.12589409, -0.96176757]])

In [ ]:
ydt_train

array([[ 0.45726087],
       [-0.78443053],
       [-0.78443053],
       ...,
       [-0.78443053],
       [-0.78443053],
       [ 0.45726087]])

##Train on different algorithms


In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [ ]:
x_pol = PolynomialFeatures(degree=2)
x_pol = x_pol.fit_transform(xdt_train)

In [ ]:
temp = PolynomialFeatures(degree=2)
temp = temp.fit_transform(xdt_test)

In [ ]:
r_reg.fit(xdt_train, ydt_train)
l_reg.fit(xdt_train, ydt_train)
d_reg.fit(xdt_train, ydt_train)
s_reg.fit(xdt_train, ydt_train)
p_reg.fit(x_pol, ydt_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_pred = r_reg.predict(xdt_test)
l_pred = l_reg.predict(xdt_test)
d_pred = d_reg.predict(xdt_test)
s_pred = s_reg.predict(xdt_test)
p_pred = p_reg.predict(temp)

##Result

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r = r2_score(ydt_test, r_pred)
l = r2_score(ydt_test, l_pred)
d = r2_score(ydt_test, d_pred)
s = r2_score(ydt_test, s_pred)
p = r2_score(ydt_test, p_pred)

In [ ]:
print('Random Forest: ' + str(r) + '\nLinear Regression: ' + str(l) + '\nDecision Tree: ' + str(d) + '\nSVR: ' + str(s)  + '\nPolynomial Features: ' + str(p))

Random Forest: 0.5298523801820614
Linear Regression: 0.42778576090157816
Decision Tree: 0.12939896174943732
SVR: 0.4439865614874138
Polynomial Features: 0.427845036365492


In [ ]:
cond = [(data['quality']>=7.5), (data['quality']<7.5)]
gb = ['Good', 'Bad']
data['review'] = np.select(cond, gb)

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  review
0               7.4             0.700         0.00  ...      9.4        5     Bad
1               7.8             0.880         0.00  ...      9.8        5     Bad
2               7.8             0.760         0.04  ...      9.8        5     Bad
3              11.2             0.280         0.56  ...      9.8        6     Bad
4               7.4             0.700         0.00  ...      9.4        5     Bad
...             ...               ...          ...  ...      ...      ...     ...
1594            6.2             0.600         0.08  ...     10.5        5     Bad
1595            5.9             0.550         0.10  ...     11.2        6     Bad
1596            6.3             0.510         0.13  ...     11.0        6     Bad
1597            5.9             0.645         0.12  ...     10.2        5     Bad
1598            6.0             0.310         0.47  ...     11.0        6     Bad

[1599 rows x 13 columns]

In [ ]:
data.iloc[300:350, :]

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  review
300            7.5             0.530         0.06  ...     10.7        6     Bad
301           11.1             0.180         0.48  ...     10.1        6     Bad
302            8.3             0.705         0.12  ...     10.0        5     Bad
303            7.4             0.670         0.12  ...      9.5        5     Bad
304            8.4             0.650         0.60  ...      9.2        5     Bad
305           10.3             0.530         0.48  ...      9.3        6     Bad
306            7.6             0.620         0.32  ...      9.4        5     Bad
307           10.3             0.410         0.42  ...      9.5        6     Bad
308           10.3             0.430         0.44  ...      9.5        6     Bad
309            7.4             0.290         0.38  ...      9.5        6     Bad
310           10.3             0.530         0.48  ...      9.3        6     Bad
311            7.9             0.530         0.24  ...      9.4        6     Bad
312            9.0             0.460         0.31  ...      9.5        6     Bad
313            8.6             0.470         0.30  ...      9.4        5     Bad
314            7.4             0.360         0.29  ...     11.0        5     Bad
315            7.1             0.350         0.29  ...     11.0        6     Bad
316            9.6             0.560         0.23  ...     10.1        5     Bad
317            9.6             0.770         0.12  ...     10.4        6     Bad
318            9.8             0.660         0.39  ...     11.5        7     Bad
319            9.6             0.770         0.12  ...     10.4        6     Bad
320            9.8             0.660         0.39  ...     11.5        7     Bad
321            9.3             0.610         0.26  ...      9.7        5     Bad
322            7.8             0.620         0.05  ...      9.3        5     Bad
323           10.3             0.590         0.42  ...      9.5        6     Bad
324           10.0             0.490         0.20  ...      9.2        6     Bad
325           10.0             0.490         0.20  ...      9.2        6     Bad
326           11.6             0.530         0.66  ...     11.5        7     Bad
327           10.3             0.440         0.50  ...     11.5        5     Bad
328           13.4             0.270         0.62  ...      9.7        6     Bad
329           10.7             0.460         0.39  ...      9.5        5     Bad
330           10.2             0.360         0.64  ...     12.5        6     Bad
331           10.2             0.360         0.64  ...     12.5        6     Bad
332            8.0             0.580         0.28  ...      9.4        6     Bad
333            8.4             0.560         0.08  ...     11.0        5     Bad
334            7.9             0.650         0.01  ...     11.7        7     Bad
335           11.9             0.695         0.53  ...     12.2        7     Bad
336            8.9             0.430         0.45  ...     12.5        6     Bad
337            7.8             0.430         0.32  ...     10.3        5     Bad
338           12.4             0.490         0.58  ...     11.5        6     Bad
339           12.5             0.280         0.54  ...      9.8        7     Bad
340           12.2             0.340         0.50  ...      9.2        6     Bad
341           10.6             0.420         0.48  ...     11.3        6     Bad
342           10.9             0.390         0.47  ...      9.8        6     Bad
343           10.9             0.390         0.47  ...      9.8        6     Bad
344           11.9             0.570         0.50  ...     10.7        6     Bad
345            7.0             0.685         0.00  ...      9.9        5     Bad
346            6.6             0.815         0.02  ...     12.3        7     Bad
347           13.8             0.490         0.67  ...     12.0        6     Bad
348            9.6             0.560